Update `Astroid` to Version `2.12.2`
AnacondaRecipes/astroid-feedstock pull request #26
Opened 2022-07-25 18:17 UTC by varlackc

`astroid` version `2.12.1`
1. - [x] Check the upstream
    https://github.com/PyCQA/astroid/tree/v2.12.1
2. - [x] Check the pinnings

`setuptools~=62.6`
`wheel~=0.37.1`
https://github.com/PyCQA/astroid/blob/v2.12.1/pyproject.toml#L2

`requires-python = ">=3.7.2"`
https://github.com/PyCQA/astroid/blob/v2.12.1/pyproject.toml#L33

3. - [x] Check the changelogs

    https://github.com/PyCQA/astroid/blob/v2.12.2/ChangeLog

    What's New in astroid 2.12.2?
=============================
Release date: 2022-07-12

* Fixed crash in modulo operations for divisions by zero.

  Closes #1700

  `Crash in modulo expression`
  https://github.com/PyCQA/astroid/issues/1700

* Fixed crash with recursion limits during inference.

  Closes #1646

  Infinite loop when inferring `from token import *`
  https://github.com/PyCQA/astroid/issues/1646

What's New in astroid 2.12.1?
=============================
Release date: 2022-07-10

* Fix a crash when inferring old-style string formatting (``%``) using tuples.

* Fix a crash when ``None`` (or a value inferred as ``None``) participates in a
  ``**`` expression.

* Fix a crash involving properties within ``if`` blocks.

4. - [x] Additional research
    https://github.com/conda-forge/astroid-feedstock/issues

    There are currently no open issues mentioned in the upstream.

5. - [x] Verify the `dev_url`
    https://github.com/PyCQA/astroid
6. - [x] Verify the `doc_url`

    https://pylint.pycqa.org/projects/astroid/en/latest/?badge=latest

7. - [x] License is `spdx` compliant
    LGPL-2.1-or-later
8. - [x] License family is present
    LGPL
9. - [x] Verify that the `build_number` is correct
10. - [x] Verify if the package needs `setuptools`
setuptools
11. - [x] Verify if the package needs `wheel`
12. - [x] `pip` in the test section
    python
13. - [x] Veriy the test section
14. - [x] Verify if the package is `architecture specific` or `Noarch`
15. - [x] Private variables are not mentioned on the recipe For example: (_private_variable)
 
Results:
- 
 
Based on the research findings and the results we can conclude
that it is safe to update `astroid` to version `2.12.1`

2022-07-25 18:46 UTC, chenghlee requested changes

2022-07-25 18:46 UTC, chenghlee commented on recipe/meta.yaml
> +    - wheel !=0.37.1
`!=` (here) and `~=` (from the upstream requirements) are _not_ the same operator. (In fact, there are almost direct opposites each other semantically speaking.)

2022-07-25 18:46 UTC, chenghlee commented on recipe/meta.yaml
> +    - setuptools !=62.6
!= (here) and ~= (from the upstream specs) are not the same operator. (In fact, there are almost direct opposites each other semantically speaking.)

2022-07-25 19:22 UTC, ryanskeith commented
LGTM

2022-07-26 08:01 UTC, skupr-anaconda commented
Before uploading v2.12.2 we have to build and upload v2.11.7 https://github.com/PyCQA/astroid/tree/v2.11.7 for pylint 2.14.5, see https://github.com/PyCQA/pylint/blob/566ffca72a1a08c9e7ec14383c4710d64165c592/setup.cfg#L50

2022-08-04 17:25 UTC, cbouss approved these changes
LGTM

2022-08-05 05:34 UTC, skupr-anaconda approved these changes

2022-08-09 21:38 UTC, merged